(define (problem hard)
  (:domain blocksworld)
  (:objects a - isBlock b - isBlock c - isBlock)
  (:init (on c a) (ontable a) (ontable b) (clear b) (clear c) (handempty))
  (:goal (and (on b c) (on a b)))
)