(define (problem jug-pouring-example)
	(:domain jug-pouring)
	(:objects
		jug-19l jug-13l jug-7l - jug)
	(:init
		(= (pour-counter) 0)
		(= (capacity jug-19l) 19)
		(= (capacity jug-13l) 13)
		(= (capacity jug-7l) 7)
		(= (amount jug-19l) 0)
		(= (amount jug-13l) 13)
		(= (amount jug-7l) 7))
	(:goal (and (= (amount jug-19l) 10)
		(= (amount jug-13l) 10)
		(= (amount jug-7l) 0)))
	(:metric minimize (pour-counter))
)