global ta ta_p as aa aa_p S c sigma
ta = 0.53;       
ta_p = 0.06;
as = 0.19;
aa = 0.30;
aa_p = 0.31;
S  = 1366;              % W/m^2
c  = 2.7;               % Wm-2K-1
sigma = 5.67 * (10^-8); % W/m^2K^4
Ts = 273;               % start with 0 deg. of Celsius
Ta = 273;               % surface and atmosphere
Xp = [Ts Ta];
X = fsolve(@heatfun, Xp);
output = [
    'Mean earth temperature with atmosphere in:', newline, ...
    '  Kelvins: ', num2str(X(1)), ' K' newline, ...
    '  Celsius: ', num2str(X(1) - 273.15), ' deg of C', newline ...
    'Mean atmosphere temperature in:', newline, ...
    '  Kelvins: ', num2str(X(2)), ' K' newline, ...
    '  Celsius: ', num2str(X(2) - 273.15), ' deg of C' newline
];
disp(output);

function F = heatfun(x)
    global ta as aa S c sigma ta_p aa_p
    F = [ -1 * ta * (1 - as) * (S/4) + ...
            c * (x(1) - x(2)) + ...
            sigma * (x(1) ^ 4) * (1 - aa_p) ...
            - sigma * (x(2) ^ 4);
          -1 * (1 - aa - ta + as*ta) * S / 4 ...
            - c * (x(1) - x(2)) ...
            - sigma * (x(1) ^ 4) * (1 - ta_p - aa_p) ...
            + 2 * sigma * x(2)^4;
        ];
end